// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNaFcl6yVrBIY9v0W60BBZBpnt_1enmsI',
    appId: '1:1000237426138:web:cfd2b84e29045f23edcce3',
    messagingSenderId: '1000237426138',
    projectId: 'cityguide-e7ab1',
    authDomain: 'cityguide-e7ab1.firebaseapp.com',
    databaseURL: 'https://cityguide-e7ab1-default-rtdb.firebaseio.com',
    storageBucket: 'cityguide-e7ab1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB56OTXIgdxG0XujOQO10OWwuYU0NLWWeA',
    appId: '1:1000237426138:android:af1b14b1263652ceedcce3',
    messagingSenderId: '1000237426138',
    projectId: 'cityguide-e7ab1',
    databaseURL: 'https://cityguide-e7ab1-default-rtdb.firebaseio.com',
    storageBucket: 'cityguide-e7ab1.firebasestorage.app',
  );
}
